# Generated by Django 2.2.4 on 2019-08-27 10:46

import csv

from django.db import migrations


def add_customers_forwards(apps, schema_editor):
    """Set site domain and name."""
    Customer = apps.get_model("crm", "Customer")
    file = open('worktest/crm/migrations/customers.csv', "rU")
    reader = csv.reader(file, delimiter=',')
    for row in reader:
        Customer.objects.create(name=row[0], email=row[1])


def add_customers_backwards(apps, schema_editor):
    Customer = apps.get_model("crm", "Customer")
    Customer.objects.delete()


class Migration(migrations.Migration):
    dependencies = [("crm", "0001_initial")]

    operations = [migrations.RunPython(add_customers_forwards, add_customers_backwards)]
